### PR TITLE
[fix] #44: Made 'tps' a positive float

### LINKED ISSUE #44: Make `tps` a positive floating point
Currently, the user can specify `tps` (transactions per second) as zero or negative. It's incorrect and may lead to bugs. We have to check the correctness of this parameter at the type level. It seems `tps` should be a positive floating point number.

This is a reference to [that discussion](https://github.com/soramitsu/iroha2-longevity-load-rs/pull/35#discussion_r1012802891).

### PR DESCRIPTION
**Pull request by pesterev**
Signed-off-by: Vladimir Pesterev <pesterev@pm.me>

# Task

Closes #44 

## Changes

1. Make the `tps` flag a type-safe on the `deamon` mode.

## Author

Signed-off-by: Vladimir Pesterev <pesterev@soramitsu.co.jp>

### CODE REVIEW

File: src/number.rs [hunk 1]
```diff
@@ -0,0 +1,51 @@
+use serde::{de::Visitor, Deserialize, Deserializer};
```
Comment (appetrosyan) [inline src/number.rs:1]: Consider adding this to iroha2:main. All of our floats are positive.

**Review by appetrosyan — APPROVED** [review]

File: src/number.rs (hunk 1 above)
Comment (pesterev) [reply src/number.rs:1]: [Opened an issue](https://github.com/hyperledger/iroha/issues/2950)
